### ISSUE TITLE
additionalProperties wrong map type

### ISSUE THREAD

**Issue by auzhva** [googleapis/gnostic-go-generator#30]
Hi,

In Swagger model I have following construct:

```yaml
someAttributes:
        type: object
        description: someAttributes
        additionalProperties:
          type: string
```

Then I'm trying to build this model with `gnostic-go-generator` it produces below model
```json
{
      "name": "someAttributes",
      "fields": [
        {
          "name": "additional_properties",
          "type": "map[string]string",
          "kind": 1,
          "native_type": "Map[String]String",
          "field_name": "AdditionalProperties",
          "parameter_name": "additional_properties"
        }
      ],
      "type_name": "SomeAttributes"
    },
```

Type Map[String]String is invalid in Go, so it results in broken `types.go` file
